#!/bin/sh
case $1 in
    resume|thaw)
        logger -t pm 'Loading facetimehd kernel module'
        /sbin/rmmod bdc_pci
        /sbin/modprobe facetimehd
        ;;
    suspend|hibernate)
        logger -t pm 'Removing facetimehd kernel module'
        /sbin/rmmod facetimehd
        exit 0
        ;;
esac
